#include "./BRepOffsetAPI/BRepOffsetAPI_DraftAngle.h"
// #include "./BRepOffsetAPI/BRepOffsetAPI_FindContigousEdges.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_MakeDraft.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_MakeEvolved.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_MakeFilling.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_MakeOffset.h"
// #include "./BRepOffsetAPI/BRepOffsetAPI_MakeOffsetShape.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_MakePipe.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_MakePipeShell.h"
// #include "./BRepOffsetAPI/BRepOffsetAPI_MakeThickSolid.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_MiddlePath.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_NormalProjection.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_SequenceOfSequenceOfReal.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_SequenceOfSequenceOfShape.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_Sewing.h"
#include "./BRepOffsetAPI/BRepOffsetAPI_ThruSections.h"
