#include "./BRep/BRep_Builder.h"
#include "./BRep/BRep_Curve3D.h"
#include "./BRep/BRep_CurveOn2Surfaces.h"
#include "./BRep/BRep_CurveOnClosedSurface.h"
#include "./BRep/BRep_CurveOnSurface.h"
#include "./BRep/BRep_CurveRepresentation.h"
#include "./BRep/BRep_GCurve.h"
#include "./BRep/BRep_ListIteratorOfListOfCurveRepresentation.h"
#include "./BRep/BRep_ListIteratorOfListOfPointRepresentation.h"
// #include "./BRep/BRep_ListOfCurveRepresentation.h"
// #include "./BRep/BRep_ListOfPointRepresentation.h"
#include "./BRep/BRep_PointOnCurve.h"
#include "./BRep/BRep_PointOnCurveOnSurface.h"
#include "./BRep/BRep_PointOnSurface.h"
#include "./BRep/BRep_PointRepresentation.h"
#include "./BRep/BRep_PointsOnSurface.h"
#include "./BRep/BRep_Polygon3D.h"
#include "./BRep/BRep_PolygonOnClosedSurface.h"
#include "./BRep/BRep_PolygonOnClosedTriangulation.h"
#include "./BRep/BRep_PolygonOnSurface.h"
#include "./BRep/BRep_PolygonOnTriangulation.h"
#include "./BRep/BRep_TEdge.h"
#include "./BRep/BRep_TFace.h"
#include "./BRep/BRep_Tool.h"
#include "./BRep/BRep_TVertex.h"
