#include "./Geom2d/Geom2d_AxisPlacement.h"
// #include "./Geom2d/Geom2d_BezierCurve.h"
#include "./Geom2d/Geom2d_BoundedCurve.h"
// #include "./Geom2d/Geom2d_BSplineCurve.h"
#include "./Geom2d/Geom2d_CartesianPoint.h"
#include "./Geom2d/Geom2d_Circle.h"
#include "./Geom2d/Geom2d_Conic.h"
#include "./Geom2d/Geom2d_Curve.h"
#include "./Geom2d/Geom2d_Direction.h"
#include "./Geom2d/Geom2d_Ellipse.h"
#include "./Geom2d/Geom2d_Geometry.h"
#include "./Geom2d/Geom2d_Hyperbola.h"
#include "./Geom2d/Geom2d_Line.h"
#include "./Geom2d/Geom2d_OffsetCurve.h"
#include "./Geom2d/Geom2d_Parabola.h"
#include "./Geom2d/Geom2d_Point.h"
#include "./Geom2d/Geom2d_Transformation.h"
#include "./Geom2d/Geom2d_TrimmedCurve.h"
#include "./Geom2d/Geom2d_UndefinedDerivative.h"
#include "./Geom2d/Geom2d_UndefinedValue.h"
#include "./Geom2d/Geom2d_Vector.h"
#include "./Geom2d/Geom2d_VectorWithMagnitude.h"
