#include "./Geom/Geom_Axis1Placement.h"
#include "./Geom/Geom_Axis2Placement.h"
#include "./Geom/Geom_AxisPlacement.h"
// #include "./Geom/Geom_BezierCurve.h"
// #include "./Geom/Geom_BezierSurface.h"
#include "./Geom/Geom_BoundedCurve.h"
#include "./Geom/Geom_BoundedSurface.h"
// #include "./Geom/Geom_BSplineCurve.h"
// #include "./Geom/Geom_BSplineSurface.h"
#include "./Geom/Geom_CartesianPoint.h"
#include "./Geom/Geom_Circle.h"
#include "./Geom/Geom_ConicalSurface.h"
#include "./Geom/Geom_Conic.h"
#include "./Geom/Geom_Curve.h"
#include "./Geom/Geom_CylindricalSurface.h"
#include "./Geom/Geom_Direction.h"
#include "./Geom/Geom_ElementarySurface.h"
#include "./Geom/Geom_Ellipse.h"
#include "./Geom/Geom_Geometry.h"
#include "./Geom/Geom_HSequenceOfBSplineSurface.h"
#include "./Geom/Geom_Hyperbola.h"
#include "./Geom/Geom_Line.h"
#include "./Geom/Geom_OffsetCurve.h"
#include "./Geom/Geom_OffsetSurface.h"
#include "./Geom/Geom_OsculatingSurface.h"
#include "./Geom/Geom_Parabola.h"
#include "./Geom/Geom_Plane.h"
#include "./Geom/Geom_Point.h"
#include "./Geom/Geom_RectangularTrimmedSurface.h"
#include "./Geom/Geom_SequenceOfBSplineSurface.h"
#include "./Geom/Geom_SphericalSurface.h"
#include "./Geom/Geom_Surface.h"
#include "./Geom/Geom_SurfaceOfLinearExtrusion.h"
#include "./Geom/Geom_SurfaceOfRevolution.h"
#include "./Geom/Geom_SweptSurface.h"
#include "./Geom/Geom_ToroidalSurface.h"
// #include "./Geom/Geom_Transformation.h"
#include "./Geom/Geom_TrimmedCurve.h"
#include "./Geom/Geom_UndefinedDerivative.h"
#include "./Geom/Geom_UndefinedValue.h"
#include "./Geom/Geom_Vector.h"
#include "./Geom/Geom_VectorWithMagnitude.h"
