class_<TopoDS_Shape>("TopoDS_Shape")
  .function("IsNull", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)() const>(&TopoDS_Shape::IsNull), allow_raw_pointers())
  .function("Nullify", reinterpret_cast<void (TopoDS_Shape::*)()>(&TopoDS_Shape::Nullify), allow_raw_pointers())
  .function("Location_1", reinterpret_cast<const TopLoc_Location & (TopoDS_Shape::*)() const>(select_overload<const TopLoc_Location & () const>(&TopoDS_Shape::Location)), allow_raw_pointers())
  .function("Location_2", reinterpret_cast<void (TopoDS_Shape::*)(const TopLoc_Location &)>(select_overload<void (const TopLoc_Location &)>(&TopoDS_Shape::Location)), allow_raw_pointers())
  .function("Located", reinterpret_cast<TopoDS_Shape (TopoDS_Shape::*)(const TopLoc_Location &) const>(&TopoDS_Shape::Located), allow_raw_pointers())
  .function("Orientation_1", reinterpret_cast<TopAbs_Orientation (TopoDS_Shape::*)() const>(select_overload<TopAbs_Orientation () const>(&TopoDS_Shape::Orientation)), allow_raw_pointers())
  .function("Orientation_2", reinterpret_cast<void (TopoDS_Shape::*)(const TopAbs_Orientation)>(select_overload<void (TopAbs_Orientation)>(&TopoDS_Shape::Orientation)), allow_raw_pointers())
  .function("Oriented", reinterpret_cast<TopoDS_Shape (TopoDS_Shape::*)(const TopAbs_Orientation) const>(&TopoDS_Shape::Oriented), allow_raw_pointers())
  .function("TShape_1", reinterpret_cast<const Handle_TopoDS_TShape & (TopoDS_Shape::*)() const>(select_overload<const Handle_TopoDS_TShape & () const>(&TopoDS_Shape::TShape)), allow_raw_pointers())
  .function("ShapeType", reinterpret_cast<TopAbs_ShapeEnum (TopoDS_Shape::*)() const>(&TopoDS_Shape::ShapeType), allow_raw_pointers())
  .function("Free_1", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)() const>(select_overload<Standard_Boolean () const>(&TopoDS_Shape::Free)), allow_raw_pointers())
  .function("Free_2", reinterpret_cast<void (TopoDS_Shape::*)(const Standard_Boolean)>(select_overload<void (Standard_Boolean)>(&TopoDS_Shape::Free)), allow_raw_pointers())
  .function("Locked_1", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)() const>(select_overload<Standard_Boolean () const>(&TopoDS_Shape::Locked)), allow_raw_pointers())
  .function("Locked_2", reinterpret_cast<void (TopoDS_Shape::*)(const Standard_Boolean)>(select_overload<void (Standard_Boolean)>(&TopoDS_Shape::Locked)), allow_raw_pointers())
  .function("Modified_1", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)() const>(select_overload<Standard_Boolean () const>(&TopoDS_Shape::Modified)), allow_raw_pointers())
  .function("Modified_2", reinterpret_cast<void (TopoDS_Shape::*)(const Standard_Boolean)>(select_overload<void (Standard_Boolean)>(&TopoDS_Shape::Modified)), allow_raw_pointers())
  .function("Checked_1", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)() const>(select_overload<Standard_Boolean () const>(&TopoDS_Shape::Checked)), allow_raw_pointers())
  .function("Checked_2", reinterpret_cast<void (TopoDS_Shape::*)(const Standard_Boolean)>(select_overload<void (Standard_Boolean)>(&TopoDS_Shape::Checked)), allow_raw_pointers())
  .function("Orientable_1", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)() const>(select_overload<Standard_Boolean () const>(&TopoDS_Shape::Orientable)), allow_raw_pointers())
  .function("Orientable_2", reinterpret_cast<void (TopoDS_Shape::*)(const Standard_Boolean)>(select_overload<void (const Standard_Boolean)>(&TopoDS_Shape::Orientable)), allow_raw_pointers())
  .function("Closed_1", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)() const>(select_overload<Standard_Boolean () const>(&TopoDS_Shape::Closed)), allow_raw_pointers())
  .function("Closed_2", reinterpret_cast<void (TopoDS_Shape::*)(const Standard_Boolean)>(select_overload<void (Standard_Boolean)>(&TopoDS_Shape::Closed)), allow_raw_pointers())
  .function("Infinite_1", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)() const>(select_overload<Standard_Boolean () const>(&TopoDS_Shape::Infinite)), allow_raw_pointers())
  .function("Infinite_2", reinterpret_cast<void (TopoDS_Shape::*)(const Standard_Boolean)>(select_overload<void (Standard_Boolean)>(&TopoDS_Shape::Infinite)), allow_raw_pointers())
  .function("Convex_1", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)() const>(select_overload<Standard_Boolean () const>(&TopoDS_Shape::Convex)), allow_raw_pointers())
  .function("Convex_2", reinterpret_cast<void (TopoDS_Shape::*)(const Standard_Boolean)>(select_overload<void (Standard_Boolean)>(&TopoDS_Shape::Convex)), allow_raw_pointers())
  .function("Move", reinterpret_cast<void (TopoDS_Shape::*)(const TopLoc_Location &)>(&TopoDS_Shape::Move), allow_raw_pointers())
  .function("Moved", reinterpret_cast<TopoDS_Shape (TopoDS_Shape::*)(const TopLoc_Location &) const>(&TopoDS_Shape::Moved), allow_raw_pointers())
  .function("Reverse", reinterpret_cast<void (TopoDS_Shape::*)()>(&TopoDS_Shape::Reverse), allow_raw_pointers())
  .function("Reversed", reinterpret_cast<TopoDS_Shape (TopoDS_Shape::*)() const>(&TopoDS_Shape::Reversed), allow_raw_pointers())
  .function("Complement", reinterpret_cast<void (TopoDS_Shape::*)()>(&TopoDS_Shape::Complement), allow_raw_pointers())
  .function("Complemented", reinterpret_cast<TopoDS_Shape (TopoDS_Shape::*)() const>(&TopoDS_Shape::Complemented), allow_raw_pointers())
  .function("Compose", reinterpret_cast<void (TopoDS_Shape::*)(const TopAbs_Orientation)>(&TopoDS_Shape::Compose), allow_raw_pointers())
  .function("Composed", reinterpret_cast<TopoDS_Shape (TopoDS_Shape::*)(const TopAbs_Orientation) const>(&TopoDS_Shape::Composed), allow_raw_pointers())
  .function("NbChildren", reinterpret_cast<Standard_Integer (TopoDS_Shape::*)() const>(&TopoDS_Shape::NbChildren), allow_raw_pointers())
  .function("IsPartner", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)(const TopoDS_Shape &) const>(&TopoDS_Shape::IsPartner), allow_raw_pointers())
  .function("IsSame", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)(const TopoDS_Shape &) const>(&TopoDS_Shape::IsSame), allow_raw_pointers())
  .function("IsEqual", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)(const TopoDS_Shape &) const>(&TopoDS_Shape::IsEqual), allow_raw_pointers())
  .function("IsNotEqual", reinterpret_cast<Standard_Boolean (TopoDS_Shape::*)(const TopoDS_Shape &) const>(&TopoDS_Shape::IsNotEqual), allow_raw_pointers())
  .function("HashCode", reinterpret_cast<Standard_EXPORT Standard_Integer (TopoDS_Shape::*)(const Standard_Integer) const>(&TopoDS_Shape::HashCode), allow_raw_pointers())
  .function("EmptyCopy", reinterpret_cast<void (TopoDS_Shape::*)()>(&TopoDS_Shape::EmptyCopy), allow_raw_pointers())
  .function("EmptyCopied", reinterpret_cast<TopoDS_Shape (TopoDS_Shape::*)() const>(&TopoDS_Shape::EmptyCopied), allow_raw_pointers())
  .function("TShape_2", reinterpret_cast<void (TopoDS_Shape::*)(const Handle_TopoDS_TShape &)>(select_overload<void (const Handle_TopoDS_TShape &)>(&TopoDS_Shape::TShape)), allow_raw_pointers())
  .function("DumpJson", reinterpret_cast<Standard_EXPORT void (TopoDS_Shape::*)(const Standard_OStream &, const Standard_Integer) const>(&TopoDS_Shape::DumpJson), allow_raw_pointers())
;
  overloadedConstructor(TopoDS_Shape, TopoDS_Shape_1, (), (), ());
  // overloadedConstructor(TopoDS_Shape, TopoDS_Shape_2, (T2 & & theOther, typename std::enable_if<opencascade::std::is_base_of<TopoDS_Shape, T2>::value>::type *), (theOther, *), (T2 & &, typename std::enable_if<opencascade::std::is_base_of<TopoDS_Shape, T2>::value>::type));
