class_<TopoDS>("TopoDS")
  .class_function("Vertex_1", reinterpret_cast< const TopoDS_Vertex & (*)(const TopoDS_Shape &)>(select_overload< const TopoDS_Vertex & (const TopoDS_Shape &)>(&TopoDS::Vertex)), allow_raw_pointers())
  // .class_function("Vertex_2", reinterpret_cast<  TopoDS_Vertex & (*)(const TopoDS_Shape)>(select_overload<  TopoDS_Vertex & (TopoDS_Shape)>(&TopoDS::Vertex)), allow_raw_pointers())
  .class_function("Edge_1", reinterpret_cast< const TopoDS_Edge & (*)(const TopoDS_Shape &)>(select_overload< const TopoDS_Edge & (const TopoDS_Shape &)>(&TopoDS::Edge)), allow_raw_pointers())
  // .class_function("Edge_2", reinterpret_cast<  TopoDS_Edge & (*)(const TopoDS_Shape)>(select_overload<  TopoDS_Edge & (TopoDS_Shape)>(&TopoDS::Edge)), allow_raw_pointers())
  .class_function("Wire_1", reinterpret_cast< const TopoDS_Wire & (*)(const TopoDS_Shape &)>(select_overload< const TopoDS_Wire & (const TopoDS_Shape &)>(&TopoDS::Wire)), allow_raw_pointers())
  // .class_function("Wire_2", reinterpret_cast<  TopoDS_Wire & (*)(const TopoDS_Shape)>(select_overload<  TopoDS_Wire & (TopoDS_Shape)>(&TopoDS::Wire)), allow_raw_pointers())
  .class_function("Face_1", reinterpret_cast< const TopoDS_Face & (*)(const TopoDS_Shape &)>(select_overload< const TopoDS_Face & (const TopoDS_Shape &)>(&TopoDS::Face)), allow_raw_pointers())
  // .class_function("Face_2", reinterpret_cast<  TopoDS_Face & (*)(const TopoDS_Shape)>(select_overload<  TopoDS_Face & (TopoDS_Shape)>(&TopoDS::Face)), allow_raw_pointers())
  .class_function("Shell_1", reinterpret_cast< const TopoDS_Shell & (*)(const TopoDS_Shape &)>(select_overload< const TopoDS_Shell & (const TopoDS_Shape &)>(&TopoDS::Shell)), allow_raw_pointers())
  // .class_function("Shell_2", reinterpret_cast<  TopoDS_Shell & (*)(const TopoDS_Shape)>(select_overload<  TopoDS_Shell & (TopoDS_Shape)>(&TopoDS::Shell)), allow_raw_pointers())
  .class_function("Solid_1", reinterpret_cast< const TopoDS_Solid & (*)(const TopoDS_Shape &)>(select_overload< const TopoDS_Solid & (const TopoDS_Shape &)>(&TopoDS::Solid)), allow_raw_pointers())
  // .class_function("Solid_2", reinterpret_cast<  TopoDS_Solid & (*)(const TopoDS_Shape)>(select_overload<  TopoDS_Solid & (TopoDS_Shape)>(&TopoDS::Solid)), allow_raw_pointers())
  .class_function("CompSolid_1", reinterpret_cast< const TopoDS_CompSolid & (*)(const TopoDS_Shape &)>(select_overload< const TopoDS_CompSolid & (const TopoDS_Shape &)>(&TopoDS::CompSolid)), allow_raw_pointers())
  // .class_function("CompSolid_2", reinterpret_cast<  TopoDS_CompSolid & (*)(const TopoDS_Shape)>(select_overload<  TopoDS_CompSolid & (TopoDS_Shape)>(&TopoDS::CompSolid)), allow_raw_pointers())
  .class_function("Compound_1", reinterpret_cast< const TopoDS_Compound & (*)(const TopoDS_Shape &)>(select_overload< const TopoDS_Compound & (const TopoDS_Shape &)>(&TopoDS::Compound)), allow_raw_pointers())
  // .class_function("Compound_2", reinterpret_cast<  TopoDS_Compound & (*)(const TopoDS_Shape)>(select_overload<  TopoDS_Compound & (TopoDS_Shape)>(&TopoDS::Compound)), allow_raw_pointers())
;
